#!/bin/bash
# Quick Start Guide for Scopa Game

echo "╔════════════════════════════════════════════════════════════╗"
echo "║          Scopa Card Game - Quick Start Guide               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This guide will help you run the complete Scopa game."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 1: Start the Java Backend Server"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Open a new terminal and run:"
echo "  cd scopa"
echo "  ./run_server.sh"
echo ""
echo "Or manually:"
echo "  cd scopa"
echo "  mvn clean compile"
echo "  mvn exec:java -Dexec.mainClass=\"com.example.scopa.server.GameServer\""
echo ""
echo "Wait for: 'Scopa GameServer: listening on port 5000'"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 2: Start the Python Frontend"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Open another terminal and run:"
echo "  cd scopa-panda3d/frontend"
echo "  ./run_frontend.sh"
echo ""
echo "Or manually:"
echo "  cd scopa-panda3d/frontend"
echo "  python3 -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo "  python scopa_game.py"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 3: Play the Game"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "In the Panda3D window:"
echo "  1. Click 'Start Game' button"
echo "  2. Use keyboard keys 1, 2, or 3 to play cards"
echo "     - Bottom row = Player 1's hand"
echo "     - Top row = Player 2's hand"
echo "     - Middle = Table cards"
echo "  3. Take turns until all cards are played"
echo "  4. Click 'Finalize Round' when done"
echo "  5. Click 'Show Score' to see results"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Testing Without Frontend"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "You can test the backend without Panda3D:"
echo "  cd scopa-panda3d/frontend"
echo "  python3 test_server.py"
echo ""
echo "This will run automated tests of the game protocol."
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Game Rules Summary"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "• Each player gets 3 cards, 4 go on the table"
echo "• Play a card to capture cards that match its value"
echo "• Exact match rule: Must capture single matching card if available"
echo "• Otherwise: Capture any combination that sums to your card's value"
echo "• Scopa: Clear the table = bonus point"
echo "• Scoring:"
echo "    - Most cards: 1 point"
echo "    - Most coins: 1 point"
echo "    - 7 of Coins (Sette Bello): 1 point"
echo "    - Primiera: 1 point (complex calculation)"
echo "    - Each Scopa: 1 point"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Troubleshooting"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Backend won't start:"
echo "  • Check Java 17+ is installed: java -version"
echo "  • Check Maven is installed: mvn -version"
echo "  • Run tests: cd scopa && mvn test"
echo ""
echo "Frontend won't start:"
echo "  • Check Python 3.8+ is installed: python3 --version"
echo "  • Install Panda3D: pip install panda3d"
echo "  • Backend must be running first"
echo ""
echo "Connection refused:"
echo "  • Make sure backend is running on port 5000"
echo "  • Check firewall settings"
echo "  • Try: telnet localhost 5000"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Documentation"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "• README.md - Complete project documentation"
echo "• IMPLEMENTATION_SUMMARY.md - Technical details"
echo "• scopa-panda3d/README.md - Frontend/backend guide"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Ready to play! Follow the steps above to start."
echo ""
